### PR TITLE
Feat/python solutions

### PR DESCRIPTION
**Pull request by oseme-techguy**
Hey @mykeels, I had wanted to collaborate with you on something and then I saw this project and just couldn't resist :-) . This is my contribution to your nobel cause:

**Changes:**  
- chore: added the Python directories
- feat: added the solution to the first question
- feat: added the solution to the second question
- feat: added the solution to the third question
- feat: added the solution to the fourth question
- feat: added the solution to the fifth question
- feat: added the solution to the sixth question
- chore: moved the solutions into their correct directory
- chore: added the completed solutions correct directory to version control
- feat: added the solution to the eight question
- chore: added the sample data for the questions
- feat: added the solution to the ninth question
- feat: added the solution to the tenth question
- feat: added the solution to question 11
- feat: added the solution to question 12
- feat: added the solution to question 13
- feat: added the solution to question 15
- feat: added the solution to question 16
- feat: added the solution to question 17
- feat: added the solution to question 18
- feat: added the solution to question 19
- feat: added the solution to question 14
- feat: added the solution to question 20

### CODE REVIEW

**Comment by mykeels** [comment]
### Dope!!!

Here's my feedback:

1. 02-lottery.py should repeat forever, till the user closes the program.

2. 03-word-in-reverse.py should repeat forever, till the user closes the program.

3. 04-type-in-reverse.py should repeat forever, till the user closes the program.

4. See 14-number-in-words.py results:

```txt
3456 => three thousand, four hundred fifty-six
13456789 => thirteen million, four hundred fifty-six thousand, seven hundred eighty-nine
```

Notice the distinct lack of `and` between the words.

5. 20-love-calculator.py gave me 106% percent for inputs 'Mike' and `Grace`. The output should be `92%` for both inputs.

6. 20-love-calculator.py should repeat forever, till the user closes the program.

**Comment by oseme-techguy** [comment]
Thanks for the pointers man. Would push an update asap to fix them!

**Comment by oseme-techguy** [comment]
Hey @mykeels, I have pushed the fixes. Please check them out. Thanks.

**Comment by mykeels** [comment]
Thanks, @oseme-techguy!

**Pull request merged**
