### PR TITLE
React Answers 

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Almost done. Have about 5 questions remaining. 

Just thought to create this incase you want to look through.

### CODE REVIEW

**Comment by mykeels** [comment]
Awesome work!!!

Looks good. I'll check again in the morning sha.

**Comment by mykeels** [comment]
So cool!

1. Can each question-component have its own route? E.g. `/01-name-concatenation`? 

2. The following answers:

- Type in reverse
- RGB color generator
- Hex color generator

should have a "Repeat" button or something.

3. The Number to words answer is missing an `"and"`.

image

it should be `three thousand four hundred and fifty-one`.

4. Compound Interest is missing a "Go Home!" button.

5. Each answer page should display the question title. E.g. `01 Name Concatenation`, because it gets difficult to differentiate `Convert to Decimal` from `Convert from Decimal to Base N`.

**Comment by BolajiOlajide** [comment]
On it. @rotimi-babalola was kind enough to help out because I've been so busy and haven't add time to complete this. I'm working on the feedback now. Thanks

**Comment by BolajiOlajide** [comment]
@mykeels This is now completed!

**Comment by BolajiOlajide** [comment]
I made the UI a bit cleaner sha

Screenshot 2019-06-13 at 12 44 49 AM
Screenshot 2019-06-13 at 12 45 13 AM

**Comment by mykeels** [comment]
Dope!

Just a few more changes.

1. The output is "below the fold" on my display, i.e. it's not obvious. Could it be above the "First name" field? Or perhaps, the question field be below, or be collapsible?

image

2. The number-to-words is still missing an "and".

image

**Comment by BolajiOlajide** [comment]
Fixed the two things you posted/

Screenshot 2019-06-17 at 12 56 04 AM

**Comment by mykeels** [comment]
See the [Algorithm I used](https://stackoverflow.com/a/3299672/7396801).

1. Should be "One hundred thousand". I believe "Lakhs" is Indian. 

image

2. Also, should have "Million" and "Billion", at least.

image

**Comment by mykeels** [comment]
Thanks @BolajiOlajide!

**Pull request merged**
