### PR TITLE
ANSWERS

### PR DESCRIPTION
**Pull request by sixofife**
This PR contains answers to the "20-questions" in Node-JS. It contains a readme file to help beginners and also text files have been created.

### CODE REVIEW

**Comment by mykeels** [comment]
### Awesome work!

A few things to note:

1. The directory format for your answers should be `answers/NodeJS/@CFCIfe`

2. The format for your answer files should be consistent. I suggest `01-name-concatenation.js`, just like the original question files. Note using `01` instead of `1` as the prefix, for ordering.

3. Each answer file should be executable e.g. `node 01-name-concatenation.js` should run with the prompts. I understand it currently exports the function that does that, but it should be executable instead.

**Comment by sixofife** [comment]
Done that.

**Comment by mykeels** [comment]
Now, I can't find your answers, and it looks like the entire `programming` folder of questions got deleted.

**Comment by sixofife** [comment]
Please check. Made a new PR enitirely. Close.

**Pull request closed without merging**
